### PR TITLE
Don't scan caps for vm blocks that have not cap_read/write access

### PR DESCRIPTION
**Pull request by InterestedInTechAndCake**

### CODE REVIEW

**Comment by InterestedInTechAndCake** [comment]
If the vm object does not have the VM_PROT_READ_CAP or VM_PROT_WRITE_CAP permissions we can skip the capability scanning on that vm block. Otherwise we would have the risk of scanning a very large swap space.

**Comment by InterestedInTechAndCake** [comment]
Tested the number of caps stored on the db before and after this change on the same process, the numbers match.

**Review by brooksdavis — APPROVED** [review]
This is fine if not quite technically correct. Theoretically a page could contain capabilities while being configured to disallow access which could then be restored later, but we don't currently expose the right state to address that (and I don't know of a way to put the system in the problemnat state with current kernel APIs). https://github.com/CTSRD-CHERI/cheribsd/pull/1916 will provide a more correct mechanism.

**Comment by psjm3** [comment]
Thanks. I have raised a new issue to implement a more proper way to handle this when https://github.com/CTSRD-CHERI/cheribsd/pull/1916 is ready.

**Pull request merged**
